### ISSUE TITLE
Couldnt get it to work

### ISSUE THREAD

**Issue by Erinio** [RD17/TeleJS#1]
Hello i couldn't get this to work with my project
What i did is npm install telejs
made a file called app.js
Used the example below didn't work

**Comment by fpd4444** [comment]
Hello @Erinio 
Please provide the sources of your example and logs of it crashing

**Comment by Erinio** [comment]
Hello @fpd4444 am using the example you guy's provided 
`import fs from 'fs'
import { MtpProxy } from 'telejs'

MtpProxy.init(
  (state) => new Promise((resolve, reject) => {
    fs.writeFile('state.json', state, 'utf8', (err) => {
      if (err) {
        reject(err)
        return
      }
      resolve()
    })
  }),
  () => new Promise((resolve, reject) => {
    fs.readFile('state.json', 'utf8', (err, data) => {
      if (err) {
        reject(err)
        return
      }
      resolve(data)
    })
  })
  , 'verbose')`

**Comment by Erinio** [comment]
@fpd4444  Log of it crashing.

```
untitled folder/app.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs'
                                                                     ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)

```

**Comment by fpd4444** [comment]
You seem to be trying to start this code as a plain node.js app - it won't work this way since it's ES6 syntax

**Comment by Erinio** [comment]
Guess your not going to help thanks anyway.
